server:
  port: 8676
spring:
  application:
    name: service-zuul
  profiles:
    active: dev

eureka:
  client:
    serviceUrl:
     defaultZone: http://localhost:8671/eureka/
zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: service-ribbon
    api-b:
      path: /api-b/**
      serviceId: service-feign
logging:
 config: classpath:logback-spring.xml
 level:
   root: info
 path: F:/data/logs
